// <auto-generated />
using System;
using GestaoOficinas.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestaoOficinas.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251102011749_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GestaoOficinas.Domain.Entities.Aluno", b =>
                {
                    b.Property<int>("IdAluno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAluno"));

                    b.Property<string>("EmailAluno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdTurma")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NascimentoAluno")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NomeAluno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RaAluno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TelefoneAluno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdAluno");

                    b.HasIndex("IdTurma");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("GestaoOficinas.Domain.Entities.Chamada", b =>
                {
                    b.Property<int>("IdChamada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdChamada"));

                    b.Property<DateTime>("DataChamada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdTurma")
                        .HasColumnType("integer");

                    b.HasKey("IdChamada");

                    b.HasIndex("IdTurma");

                    b.ToTable("Chamadas");
                });

            modelBuilder.Entity("GestaoOficinas.Domain.Entities.Documento", b =>
                {
                    b.Property<int>("IdDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDocumento"));

                    b.Property<DateTime>("Emissao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("IdAluno")
                        .HasColumnType("integer");

                    b.Property<int?>("IdEscola")
                        .HasColumnType("integer");

                    b.Property<int>("IdOficina")
                        .HasColumnType("integer");

                    b.Property<string>("StatusDocumento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdDocumento");

                    b.HasIndex("IdAluno");

                    b.HasIndex("IdEscola");

                    b.HasIndex("IdOficina");

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("GestaoOficinas.Domain.Entities.Escola", b =>
                {
                    b.Property<int>("IdEscola")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEscola"));

                    b.Property<string>("CepEscola")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CnpjEscola")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ComplementoEscola")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmailEscola")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeEscola")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RuaEscola")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TelefoneEscola")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdEscola");

                    b.ToTable("Escolas");
                });

            modelBuilder.Entity("GestaoOficinas.Domain.Entities.Inscricao", b =>
                {
                    b.Property<int>("IdAluno")
                        .HasColumnType("integer");

                    b.Property<int>("IdTurma")
                        .HasColumnType("integer");

                    b.Property<string>("StatusInscricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdAluno", "IdTurma");

                    b.HasIndex("IdTurma");

                    b.ToTable("Inscricoes");
                });

            modelBuilder.Entity("GestaoOficinas.Domain.Entities.Oficina", b =>
                {
                    b.Property<int>("IdOficina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdOficina"));

                    b.Property<int>("CargaHorariaOficinia")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataOficina")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DescricaoOficina")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdProfessor")
                        .HasColumnType("integer");

                    b.Property<string>("NomeOficina")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusOficina")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TemaOficina")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdOficina");

                    b.HasIndex("IdProfessor");

                    b.ToTable("Oficinas");
                });

            modelBuilder.Entity("GestaoOficinas.Domain.Entities.OficinaTutor", b =>
                {
                    b.Property<int>("IdOficina")
                        .HasColumnType("integer");

                    b.Property<int>("IdProfessor")
                        .HasColumnType("integer");

                    b.HasKey("IdOficina", "IdProfessor");

                    b.HasIndex("IdProfessor");

                    b.ToTable("OficinaTutores");
                });

            modelBuilder.Entity("GestaoOficinas.Domain.Entities.Presenca", b =>
                {
                    b.Property<int>("IdAluno")
                        .HasColumnType("integer");

                    b.Property<int>("IdChamada")
                        .HasColumnType("integer");

                    b.Property<bool>("Presente")
                        .HasColumnType("boolean");

                    b.HasKey("IdAluno", "IdChamada");

                    b.HasIndex("IdChamada");

                    b.ToTable("Presencas");
                });

            modelBuilder.Entity("GestaoOficinas.Domain.Entities.Professor", b =>
                {
                    b.Property<int>("IdProfessor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProfessor"));

                    b.Property<string>("CargoProfessor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConhecimentoProfessor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmailProfessor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdEscola")
                        .HasColumnType("integer");

                    b.Property<string>("NomeProfessor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Representante")
                        .HasColumnType("boolean");

                    b.Property<string>("TelefoneProfessor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdProfessor");

                    b.HasIndex("IdEscola");

                    b.ToTable("Professores");
                });

            modelBuilder.Entity("GestaoOficinas.Domain.Entities.Turma", b =>
                {
                    b.Property<int>("IdTurma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTurma"));

                    b.Property<int>("IdOficina")
                        .HasColumnType("integer");

                    b.Property<string>("NomeTurma")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PeriodoTurma")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SemestreTurma")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdTurma");

                    b.HasIndex("IdOficina");

                    b.ToTable("Turmas");
                });

            modelBuilder.Entity("GestaoOficinas.Domain.Entities.Aluno", b =>
                {
                    b.HasOne("GestaoOficinas.Domain.Entities.Turma", "Turma")
                        .WithMany("Alunos")
                        .HasForeignKey("IdTurma")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("GestaoOficinas.Domain.Entities.Chamada", b =>
                {
                    b.HasOne("GestaoOficinas.Domain.Entities.Turma", "Turma")
                        .WithMany("Chamadas")
                        .HasForeignKey("IdTurma")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("GestaoOficinas.Domain.Entities.Documento", b =>
                {
                    b.HasOne("GestaoOficinas.Domain.Entities.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("IdAluno");

                    b.HasOne("GestaoOficinas.Domain.Entities.Escola", "Escola")
                        .WithMany()
                        .HasForeignKey("IdEscola");

                    b.HasOne("GestaoOficinas.Domain.Entities.Oficina", "Oficina")
                        .WithMany("Documentos")
                        .HasForeignKey("IdOficina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Escola");

                    b.Navigation("Oficina");
                });

            modelBuilder.Entity("GestaoOficinas.Domain.Entities.Inscricao", b =>
                {
                    b.HasOne("GestaoOficinas.Domain.Entities.Aluno", "Aluno")
                        .WithMany("Inscricoes")
                        .HasForeignKey("IdAluno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoOficinas.Domain.Entities.Turma", "Turma")
                        .WithMany("Inscricoes")
                        .HasForeignKey("IdTurma")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("GestaoOficinas.Domain.Entities.Oficina", b =>
                {
                    b.HasOne("GestaoOficinas.Domain.Entities.Professor", "ProfessorResponsavel")
                        .WithMany("OficinasResponsavel")
                        .HasForeignKey("IdProfessor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProfessorResponsavel");
                });

            modelBuilder.Entity("GestaoOficinas.Domain.Entities.OficinaTutor", b =>
                {
                    b.HasOne("GestaoOficinas.Domain.Entities.Oficina", "Oficina")
                        .WithMany("Tutores")
                        .HasForeignKey("IdOficina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoOficinas.Domain.Entities.Professor", "Professor")
                        .WithMany("OficinasComoTutor")
                        .HasForeignKey("IdProfessor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oficina");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("GestaoOficinas.Domain.Entities.Presenca", b =>
                {
                    b.HasOne("GestaoOficinas.Domain.Entities.Aluno", "Aluno")
                        .WithMany("Presencas")
                        .HasForeignKey("IdAluno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestaoOficinas.Domain.Entities.Chamada", "Chamada")
                        .WithMany("Presencas")
                        .HasForeignKey("IdChamada")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Chamada");
                });

            modelBuilder.Entity("GestaoOficinas.Domain.Entities.Professor", b =>
                {
                    b.HasOne("GestaoOficinas.Domain.Entities.Escola", "Escola")
                        .WithMany("Professores")
                        .HasForeignKey("IdEscola")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Escola");
                });

            modelBuilder.Entity("GestaoOficinas.Domain.Entities.Turma", b =>
                {
                    b.HasOne("GestaoOficinas.Domain.Entities.Oficina", "Oficina")
                        .WithMany("Turmas")
                        .HasForeignKey("IdOficina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oficina");
                });

            modelBuilder.Entity("GestaoOficinas.Domain.Entities.Aluno", b =>
                {
                    b.Navigation("Inscricoes");

                    b.Navigation("Presencas");
                });

            modelBuilder.Entity("GestaoOficinas.Domain.Entities.Chamada", b =>
                {
                    b.Navigation("Presencas");
                });

            modelBuilder.Entity("GestaoOficinas.Domain.Entities.Escola", b =>
                {
                    b.Navigation("Professores");
                });

            modelBuilder.Entity("GestaoOficinas.Domain.Entities.Oficina", b =>
                {
                    b.Navigation("Documentos");

                    b.Navigation("Turmas");

                    b.Navigation("Tutores");
                });

            modelBuilder.Entity("GestaoOficinas.Domain.Entities.Professor", b =>
                {
                    b.Navigation("OficinasComoTutor");

                    b.Navigation("OficinasResponsavel");
                });

            modelBuilder.Entity("GestaoOficinas.Domain.Entities.Turma", b =>
                {
                    b.Navigation("Alunos");

                    b.Navigation("Chamadas");

                    b.Navigation("Inscricoes");
                });
#pragma warning restore 612, 618
        }
    }
}
